### ISSUE TITLE
Card title text not completely showing up

### ISSUE THREAD

**Issue by HelloShiv** [HelloShiv/drcarewell#2]
https://github.com/HelloShiv/drcarewell/blob/76d484bed69fd9670ba2164668104ecb243d5e79/src/components/Bundle.jsx#L18      

Name is too big and is rendering with` Development Pediatric... `    same with `Psychological Assess...`

![image](https://github.com/HelloShiv/drcarewell/assets/91686009/9a6dba37-a554-4fa4-b308-56626120166b)

**Comment by Robinpn** [comment]
Hi I could fix this for you. Want to assign me to this task?
